language: ruby
rvm:
  - 2.0.0
  - 2.2.4
env:
  - WEBPORTAL_SIMULATION_MODE=true WEBPORTAL_ASYNC_MODE=true
  - WEBPORTAL_SIMULATION_MODE=true WEBPORTAL_ASYNC_MODE=false
before_script:
  - bundle exec rake db:migrate RAILS_ENV=test
script: 
  - bundle exec rspec -f d spec/requests/provisioningobjects_spec.rb "$@"
  - bundle exec rspec -f d spec/requests/system_settings_spec.rb
